// ADD ADDRESS
export const ADDRESS_ADD_REQUEST = 'ADDRESS_ADD_REQUEST'
export const ADDRESS_ADD_SUCCESS = 'ADDRESS_ADD_SUCCESS'
export const ADDRESS_ADD_FAIL = 'ADDRESS_ADD_FAIL'

// GET ADDRESSES
export const ADDRESS_LIST_REQUEST = 'ADDRESS_LIST_REQUEST'
export const ADDRESS_LIST_SUCCESS = 'ADDRESS_LIST_SUCCESS'
export const ADDRESS_LIST_FAIL = 'ADDRESS_LIST_FAIL'

// UPDATE ADDRESS
export const ADDRESS_UPDATE_REQUEST = 'ADDRESS_UPDATE_REQUEST'
export const ADDRESS_UPDATE_SUCCESS = 'ADDRESS_UPDATE_SUCCESS'
export const ADDRESS_UPDATE_FAIL = 'ADDRESS_UPDATE_FAIL'

// DELETE ADDRESS
export const ADDRESS_DELETE_REQUEST = 'ADDRESS_DELETE_REQUEST'
export const ADDRESS_DELETE_SUCCESS = 'ADDRESS_DELETE_SUCCESS'
export const ADDRESS_DELETE_FAIL = 'ADDRESS_DELETE_FAIL'

// SET DEFAULT ADDRESS
export const ADDRESS_SET_DEFAULT_REQUEST = 'ADDRESS_SET_DEFAULT_REQUEST'
export const ADDRESS_SET_DEFAULT_SUCCESS = 'ADDRESS_SET_DEFAULT_SUCCESS'
export const ADDRESS_SET_DEFAULT_FAIL = 'ADDRESS_SET_DEFAULT_FAIL'

// RESET (khi logout)
export const ADDRESS_RESET = 'ADDRESS_RESET'