export const CART_ADD_ITEM = 'CART_ADD_ITEM'
export const CART_CLEAR_ITEMS = 'CART_RESET'
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'
export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS'
export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD'
export const CART_SAVE_DELIVERY_METHOD = 'CART_SAVE_DELIVERY_METHOD'
export const CART_SAVE_VOUCHER_CODE = 'CART_SAVE_VOUCHER_CODE'
export const CART_SAVE_SHOP_MESSAGE = 'CART_SAVE_SHOP_MESSAGE'
export const CART_SAVE_DELIVERY_FEE = 'CART_SAVE_DELIVERY_FEE'
export const CART_SAVE_VOUCHER_DISCOUNT = 'CART_SAVE_VOUCHER_DISCOUNT'
export const CART_SAVE_DELIVERY_PROVIDER = 'CART_SAVE_DELIVERY_PROVIDER'

// MỚI (B8): đồng bộ lại giá giỏ hàng theo giá hiện tại của sản phẩm
// (vd Flash Sale đã hết hạn → tự trả về giá gốc)
export const CART_SYNC_PRICES = 'CART_SYNC_PRICES'