export const NOTIFICATION_LIST_REQUEST = 'NOTIFICATION_LIST_REQUEST'
export const NOTIFICATION_LIST_SUCCESS = 'NOTIFICATION_LIST_SUCCESS'
export const NOTIFICATION_LIST_FAIL = 'NOTIFICATION_LIST_FAIL'

export const NOTIFICATION_UNREAD_COUNT_SUCCESS = 'NOTIFICATION_UNREAD_COUNT_SUCCESS'

export const NOTIFICATION_MARK_READ_SUCCESS = 'NOTIFICATION_MARK_READ_SUCCESS'
export const NOTIFICATION_MARK_ALL_READ_SUCCESS = 'NOTIFICATION_MARK_ALL_READ_SUCCESS'

// ── MỚI: Thông báo cho Khách hàng (My) ──────────────────────────
export const MY_NOTIFICATION_LIST_REQUEST = 'MY_NOTIFICATION_LIST_REQUEST'
export const MY_NOTIFICATION_LIST_SUCCESS = 'MY_NOTIFICATION_LIST_SUCCESS'
export const MY_NOTIFICATION_LIST_FAIL = 'MY_NOTIFICATION_LIST_FAIL'

export const MY_NOTIFICATION_UNREAD_COUNT_SUCCESS = 'MY_NOTIFICATION_UNREAD_COUNT_SUCCESS'

export const MY_NOTIFICATION_MARK_READ_SUCCESS = 'MY_NOTIFICATION_MARK_READ_SUCCESS'
export const MY_NOTIFICATION_MARK_ALL_READ_SUCCESS = 'MY_NOTIFICATION_MARK_ALL_READ_SUCCESS'

// MỚI: xoá thông báo
export const NOTIFICATION_DELETE_SUCCESS = 'NOTIFICATION_DELETE_SUCCESS'
export const MY_NOTIFICATION_DELETE_SUCCESS = 'MY_NOTIFICATION_DELETE_SUCCESS'

// ── MỚI (B9): thông báo đẩy tới real-time qua Socket.io ─────────
export const NOTIFICATION_SOCKET_NEW = 'NOTIFICATION_SOCKET_NEW'
export const MY_NOTIFICATION_SOCKET_NEW = 'MY_NOTIFICATION_SOCKET_NEW'