export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST'
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS'
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL'
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET'

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST'
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS'
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL'

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST'
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS'
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL'
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET'

// MỚI: Admin đánh dấu đã thu/chưa thu tiền cho đơn COD
export const ORDER_COD_PAYMENT_REQUEST = 'ORDER_COD_PAYMENT_REQUEST'
export const ORDER_COD_PAYMENT_SUCCESS = 'ORDER_COD_PAYMENT_SUCCESS'
export const ORDER_COD_PAYMENT_FAIL = 'ORDER_COD_PAYMENT_FAIL'
export const ORDER_COD_PAYMENT_RESET = 'ORDER_COD_PAYMENT_RESET'

export const ORDER_LIST_MY_REQUEST = 'ORDER_LIST_MY_REQUEST'
export const ORDER_LIST_MY_SUCCESS = 'ORDER_LIST_MY_SUCCESS'
export const ORDER_LIST_MY_FAIL = 'ORDER_LIST_MY_FAIL'
export const ORDER_LIST_MY_RESET = 'ORDER_LIST_MY_RESET'

export const ORDER_LIST_REQUEST = 'ORDER_LIST_REQUEST'
export const ORDER_LIST_SUCCESS = 'ORDER_LIST_SUCCESS'
export const ORDER_LIST_FAIL = 'ORDER_LIST_FAIL'

export const ORDER_DELIVER_REQUEST = 'ORDER_DELIVER_REQUEST'
export const ORDER_DELIVER_SUCCESS = 'ORDER_DELIVER_SUCCESS'
export const ORDER_DELIVER_FAIL = 'ORDER_DELIVER_FAIL'
export const ORDER_DELIVER_RESET = 'ORDER_DELIVER_RESET'

export const ORDER_CANCEL_REQUEST_REQUEST = 'ORDER_CANCEL_REQUEST_REQUEST'
export const ORDER_CANCEL_REQUEST_SUCCESS = 'ORDER_CANCEL_REQUEST_SUCCESS'
export const ORDER_CANCEL_REQUEST_FAIL = 'ORDER_CANCEL_REQUEST_FAIL'
export const ORDER_CANCEL_REQUEST_RESET = 'ORDER_CANCEL_REQUEST_RESET'

export const ORDER_APPROVE_CANCEL_REQUEST = 'ORDER_APPROVE_CANCEL_REQUEST'
export const ORDER_APPROVE_CANCEL_SUCCESS = 'ORDER_APPROVE_CANCEL_SUCCESS'
export const ORDER_APPROVE_CANCEL_FAIL = 'ORDER_APPROVE_CANCEL_FAIL'
export const ORDER_APPROVE_CANCEL_RESET = 'ORDER_APPROVE_CANCEL_RESET'

export const ORDER_REJECT_CANCEL_REQUEST = 'ORDER_REJECT_CANCEL_REQUEST'
export const ORDER_REJECT_CANCEL_SUCCESS = 'ORDER_REJECT_CANCEL_SUCCESS'
export const ORDER_REJECT_CANCEL_FAIL = 'ORDER_REJECT_CANCEL_FAIL'
export const ORDER_REJECT_CANCEL_RESET = 'ORDER_REJECT_CANCEL_RESET'


export const ORDER_TRACK_REQUEST = 'ORDER_TRACK_REQUEST'
export const ORDER_TRACK_SUCCESS = 'ORDER_TRACK_SUCCESS'
export const ORDER_TRACK_FAIL = 'ORDER_TRACK_FAIL'
export const ORDER_TRACK_RESET = 'ORDER_TRACK_RESET'

export const ORDER_ADMIN_REVENUE_REQUEST = 'ORDER_ADMIN_REVENUE_REQUEST'
export const ORDER_ADMIN_REVENUE_SUCCESS = 'ORDER_ADMIN_REVENUE_SUCCESS'
export const ORDER_ADMIN_REVENUE_FAIL = 'ORDER_ADMIN_REVENUE_FAIL'

export const ORDER_ADMIN_BRAND_REQUEST = 'ORDER_ADMIN_BRAND_REQUEST'
export const ORDER_ADMIN_BRAND_SUCCESS = 'ORDER_ADMIN_BRAND_SUCCESS'
export const ORDER_ADMIN_BRAND_FAIL = 'ORDER_ADMIN_BRAND_FAIL'

export const ORDER_ADMIN_DELETE_REQUEST = 'ORDER_ADMIN_DELETE_REQUEST'
export const ORDER_ADMIN_DELETE_SUCCESS = 'ORDER_ADMIN_DELETE_SUCCESS'
export const ORDER_ADMIN_DELETE_FAIL = 'ORDER_ADMIN_DELETE_FAIL'
export const ORDER_ADMIN_DELETE_RESET = 'ORDER_ADMIN_DELETE_RESET'

export const ORDER_UPDATE_STATUS_REQUEST = 'ORDER_UPDATE_STATUS_REQUEST'
export const ORDER_UPDATE_STATUS_SUCCESS = 'ORDER_UPDATE_STATUS_SUCCESS'
export const ORDER_UPDATE_STATUS_FAIL = 'ORDER_UPDATE_STATUS_FAIL'
export const ORDER_UPDATE_STATUS_RESET = 'ORDER_UPDATE_STATUS_RESET'

export const REVENUE_ANALYTICS_REQUEST = 'REVENUE_ANALYTICS_REQUEST'
export const REVENUE_ANALYTICS_SUCCESS = 'REVENUE_ANALYTICS_SUCCESS'
export const REVENUE_ANALYTICS_FAIL = 'REVENUE_ANALYTICS_FAIL'

export const ORDER_REFUND_REQUEST_REQUEST = 'ORDER_REFUND_REQUEST_REQUEST'
export const ORDER_REFUND_REQUEST_SUCCESS = 'ORDER_REFUND_REQUEST_SUCCESS'
export const ORDER_REFUND_REQUEST_FAIL = 'ORDER_REFUND_REQUEST_FAIL'
export const ORDER_REFUND_REQUEST_RESET = 'ORDER_REFUND_REQUEST_RESET'

export const ORDER_REFUND_COMPLETE_REQUEST = 'ORDER_REFUND_COMPLETE_REQUEST'
export const ORDER_REFUND_COMPLETE_SUCCESS = 'ORDER_REFUND_COMPLETE_SUCCESS'
export const ORDER_REFUND_COMPLETE_FAIL = 'ORDER_REFUND_COMPLETE_FAIL'
export const ORDER_REFUND_COMPLETE_RESET = 'ORDER_REFUND_COMPLETE_RESET'