export const SHIPPING_QUOTES_REQUEST = 'SHIPPING_QUOTES_REQUEST'
export const SHIPPING_QUOTES_SUCCESS = 'SHIPPING_QUOTES_SUCCESS'
export const SHIPPING_QUOTES_FAIL = 'SHIPPING_QUOTES_FAIL'
export const SHIPPING_QUOTES_RESET = 'SHIPPING_QUOTES_RESET'

export const SHIPPING_TRACK_REQUEST = 'SHIPPING_TRACK_REQUEST'
export const SHIPPING_TRACK_SUCCESS = 'SHIPPING_TRACK_SUCCESS'
export const SHIPPING_TRACK_FAIL = 'SHIPPING_TRACK_FAIL'
export const SHIPPING_TRACK_RESET = 'SHIPPING_TRACK_RESET'

